CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    timezone VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    timezone VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_offerings_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_offerings_teacher FOREIGN KEY (teacher_id) REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id BIGINT NOT NULL,
    start_time_utc TIMESTAMPTZ NOT NULL,
    end_time_utc TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_sessions_offering FOREIGN KEY (offering_id) REFERENCES offerings(id) ON DELETE CASCADE,
    CONSTRAINT chk_sessions_end_after_start CHECK (end_time_utc > start_time_utc)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL,
    offering_id BIGINT NOT NULL,
    booked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_bookings_parent FOREIGN KEY (parent_id) REFERENCES parents(id),
    CONSTRAINT fk_bookings_offering FOREIGN KEY (offering_id) REFERENCES offerings(id),
    CONSTRAINT uq_bookings_parent_offering UNIQUE (parent_id, offering_id)
);

CREATE INDEX IF NOT EXISTS idx_teachers_timezone ON teachers(timezone);
CREATE INDEX IF NOT EXISTS idx_parents_timezone ON parents(timezone);
CREATE INDEX IF NOT EXISTS idx_offerings_course ON offerings(course_id);
CREATE INDEX IF NOT EXISTS idx_offerings_teacher ON offerings(teacher_id);
CREATE INDEX IF NOT EXISTS idx_offerings_created_at ON offerings(created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_offering ON sessions(offering_id);
CREATE INDEX IF NOT EXISTS idx_sessions_time_range ON sessions(start_time_utc, end_time_utc);
CREATE INDEX IF NOT EXISTS idx_bookings_parent ON bookings(parent_id);
CREATE INDEX IF NOT EXISTS idx_bookings_offering ON bookings(offering_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booked_at ON bookings(booked_at);

